import {randomUUID,createHash} from 'node:crypto';
import sharp from 'sharp';
import jsQR from 'jsqr';
import type {Database} from './database';
import {AppError,appOrigin,issueEntryToken} from './security';
import {getEntry,linkLine} from './store';
import type {Entry} from './prizes';
export function lineReady(){return Boolean(process.env.LINE_CHANNEL_ACCESS_TOKEN&&process.env.LINE_CHANNEL_SECRET&&process.env.NEXT_PUBLIC_LINE_OA_URL)}
export function imageMessages(entry:Entry){const token=issueEntryToken(entry.id);const image=`${appOrigin()}/api/voucher/${encodeURIComponent(token)}/image?kind=result`;return [{type:'image',originalContentUrl:image,previewImageUrl:image}];}
async function api(path:string,body:unknown,key?:string){const token=process.env.LINE_CHANNEL_ACCESS_TOKEN;if(!token)throw new Error('LINE_CHANNEL_ACCESS_TOKEN is not configured');const response=await fetch(`https://api.line.me/v2/bot/message/${path}`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`,...(key?{'X-Line-Retry-Key':key}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});if(response.ok||response.status===409&&key)return;if(response.status===429)throw new Error('LINE_QUOTA_OR_RATE_LIMIT');throw new Error(`LINE_SEND_${response.status}`);}
function retryKey(id:string){const hex=createHash('sha256').update(id).digest('hex').slice(0,32);return `${hex.slice(0,8)}-${hex.slice(8,12)}-4${hex.slice(13,16)}-a${hex.slice(17,20)}-${hex.slice(20)}`}
export function tokenFromText(text:string){return text.match(/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.[A-Za-z0-9_-]{43}/i)?.[0]??null}
export async function tokenFromImage(image:Buffer){try{const {data,info}=await sharp(image,{limitInputPixels:36_000_000}).rotate().resize({width:2000,height:2000,fit:'inside',withoutEnlargement:true}).toColourspace('srgb').ensureAlpha().raw().toBuffer({resolveWithObject:true});const decoded=jsQR(new Uint8ClampedArray(data),info.width,info.height,{inversionAttempts:'attemptBoth'});return decoded?tokenFromText(decoded.data):null}catch{throw new AppError(400,'อ่านภาพไม่ได้ กรุณาส่งรูป voucher ต้นฉบับ หรือข้อความยืนยันสิทธิ์จากเว็บ')}}
async function fetchImage(id:string){if(!/^[a-zA-Z0-9_-]+$/.test(id))throw new AppError(400,'รหัสภาพไม่ถูกต้อง');const r=await fetch(`https://api-data.line.me/v2/bot/message/${id}/content`,{headers:{Authorization:`Bearer ${process.env.LINE_CHANNEL_ACCESS_TOKEN}`},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`LINE_IMAGE_${r.status}`);const reader=r.body?.getReader();if(!reader)throw new Error('LINE_IMAGE_EMPTY');const chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>12_000_000){await reader.cancel();throw new AppError(413,'ภาพใหญ่เกินไป กรุณาส่งไฟล์ voucher ต้นฉบับจากเว็บ');}chunks.push(value)}return Buffer.concat(chunks)}
type Event={webhookEventId?:string;type:string;replyToken?:string;source?:{type?:string;userId?:string};message?:{type?:string;id?:string;text?:string};deliveryContext?:{isRedelivery?:boolean}};
export async function handleLineEvent(db:Database,event:Event){const user=event.source?.type==='user'?event.source.userId:undefined;if(!user||!event.replyToken||!event.webhookEventId)return;const eventId=event.webhookEventId;
 const claim=await db.query(`INSERT INTO webhook_events(event_id,state,leased_until) VALUES($1,'processing',now()+interval '2 minutes') ON CONFLICT(event_id) DO UPDATE SET state='processing',leased_until=now()+interval '2 minutes' WHERE webhook_events.state<>'done' AND webhook_events.leased_until<now() RETURNING event_id`,[eventId]);if(!claim.rows.length)return;
 try{let messages:unknown[];if(event.type==='follow'){messages=[{type:'text',text:'ยินดีต้อนรับ กรุณาลงทะเบียนที่เว็บของงาน แล้วส่งรูป voucher ที่ดาวน์โหลดจากเว็บในแชตนี้ ระบบจะตอบกลับเป็นรูปผลรางวัลเมื่อมีการประกาศผล'}];}
 else if(event.type==='message'){
 let token:string|null=null;let entry:Entry|undefined;
 try{if(event.message?.type==='image'&&event.message.id)token=await tokenFromImage(await fetchImage(event.message.id));else if(event.message?.type==='text')token=tokenFromText(event.message.text??'');
 if(token)entry=await linkLine(db,token,user);else if(event.message?.type==='text'&&['ผลรางวัล','รับผล','ตรวจผล'].includes((event.message.text??'').trim())){const {rows}=await db.query<{id:string}>('SELECT id FROM participants WHERE line_user_id=$1',[user]);if(rows.length)entry=await getEntry(db,issueEntryToken(rows[0].id));}
 messages=entry?imageMessages(entry):[{type:'text',text:'กรุณาส่งรูป voucher ต้นฉบับที่ดาวน์โหลดจากเว็บ โดยให้ QR ชัดเจน หรือคัดลอกข้อความยืนยันสิทธิ์จากหน้า voucher มาส่ง เมื่อผูกสิทธิ์แล้วพิมพ์ “ผลรางวัล” เพื่อตรวจผลได้'}];
 }catch(e){if(e instanceof AppError)messages=[{type:'text',text:e.message}];else throw e;}}
 else {await db.query("UPDATE webhook_events SET state='done',completed_at=now() WHERE event_id=$1",[eventId]);return;}
 try{await api('reply',{replyToken:event.replyToken,messages});}catch(e){if(e instanceof Error&&e.message==='LINE_SEND_400')await api('push',{to:user,messages},retryKey(eventId));else throw e}
 await db.query("UPDATE webhook_events SET state='done',completed_at=now() WHERE event_id=$1",[eventId]);
 }catch(e){await db.query('UPDATE webhook_events SET leased_until=now() WHERE event_id=$1',[eventId]);throw e}}
export async function deliverOutbox(db:Database,limit=15){if(!lineReady())return {sent:0,failed:0,configured:false};let sent=0,failed=0;for(let i=0;i<limit;i++){const {rows}=await db.query<{id:string;participant_id:string}>(`UPDATE line_outbox SET leased_until=now()+interval '2 minutes',attempts=attempts+1 WHERE id=(SELECT id FROM line_outbox WHERE sent_at IS NULL AND available_at<=now() AND (leased_until IS NULL OR leased_until<now()) ORDER BY available_at,id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id,participant_id`);if(!rows.length)break;const row=rows[0];try{const entry=await getEntry(db,issueEntryToken(row.participant_id));if(!entry.line_user_id)throw new Error('LINE_NOT_LINKED');await api('push',{to:entry.line_user_id,messages:imageMessages(entry)},row.id);await db.query('UPDATE line_outbox SET sent_at=now(),leased_until=NULL,last_error=NULL WHERE id=$1',[row.id]);sent++;}catch(e){await db.query("UPDATE line_outbox SET leased_until=NULL,available_at=now()+interval '1 minute',last_error=$2 WHERE id=$1",[row.id,e instanceof Error?e.message:'SEND_FAILED']);failed++;}}const remaining=Number((await db.query('SELECT count(*) AS count FROM line_outbox WHERE sent_at IS NULL')).rows[0].count);return {sent,failed,configured:true,remaining}}
